# pre-commit configuration
#
# We use pre-commit to enforce a consistency in our repositories. By default,
# YAML and Markdown files get linted, and Prettier runs to auto-format the file
# types it supports. Clippy and Rustfmt do the same for Rust files.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/jdno/pre-commit-rust
    rev: v1.1.0
    hooks:
      - id: clippy
        args: [--all-targets, --all-features, --, -D, warnings]
      - id: fmt
