---
name: Release

"on":
  release:
    types: [published]

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jdno/rust:main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish crate
        run: cargo publish -v --all-features
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
